### PR TITLE
upstream esl patch for bundle, makes install prefix usable and a miss…

### PR DESCRIPTION
**Pull request by alinelena**
…ing include for fortran

### CODE REVIEW

**Comment by zerothi** [comment]
I could however make `prefix` work as a replacement for `PREFIX`? I think that is cleaner...

**Comment by alinelena** [comment]
there is slightly more than just the change form PREFIX to prefix, which I do not know by whom was done.


---Dr Alin Marin Elenahttp://alin.elena.space

 ---- On Mon, 14 Jan 2019 21:08:03 +0000 Nick R. Papior <notifications@github.com> wrote ----

**Comment by zerothi** [comment]
@alinelena thanks.

But what about the `DESTDIR` addition?

Couldn't one simply do:

```make
make PREFIX=$DESTDIR$PREFIX
```
to get the same effect?

**Comment by zerothi** [comment]
I think this has been fixed upstream (in Smeka)

**Pull request closed without merging**
